#!/bin/bash
#
# kakoune-anywhere - use Vim whenever, wherever
# Author: Chris Knadler
# Fork: d1egoaz
# Homepage: https://www.github.com/d1egoaz/kakoune-anywhere
#
# Uninstalls kakoune-anywhere

set -e

###
# opts
###

while getopts ":v" opt; do
  case "$opt" in
    v) set -x ;;
    \?) echo "Invalid option: -$OPTARG" >&2 ;;
  esac
done

###
# defs
###

check_installed() { hash $1 &> /dev/null; }

AW_PATH=$HOME/.kakoune-anywhere
DOC_PATH=/tmp/kakoune-anywhere

###
# uninstall
###

rm -rf $AW_PATH $DOC_PATH

# Linux uninstall
if [[ $OSTYPE == "linux-gnu" ]]; then
  if check_installed gconftool; then
    kbd_path=/desktop/gnome/keybindings/kakoune-anywhere
    gconftool --unset $kbd_path/name
    gconftool --unset $kbd_path/binding
    gconftool --unset $kbd_path/action

  else # gsettings must be installed
    custom_kbd=org.gnome.settings-daemon.plugins.media-keys.custom-keybinding
    kbd_path=/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/kakoune-anywhere/
    gsettings reset-recursively $custom_kbd:$kbd_path
  fi

# OSX uninstall
elif [[ $OSTYPE == "darwin"* ]]; then
  rm -rf $HOME/Library/Services/KakouneAnywhere.workflow
fi

echo "kakoune-anywhere has been successfully uninstalled!"
